/** 보고서 출장목적·TBM 작업명 등 동일 자동완성 단어 목록 */
export const PURPOSE_AUTOCOMPLETE_OPTIONS = [
    "Replacement",
    "R&D",
    "FBIV-A",
    "Atomizer",
    "Spindle Guide",
    "Support",
    "valve",
    "Cylinder",
    "Installation",
    "cover",
    "Inspection",
    "Leakage",
    "Update",
    "Top Cover",
    "Exhasut valve",
    "Introduction",
    "Gasket",
    "Piston",
    "FBIV-M",
    "Conponent",
    "Recovery",
    "Modification",
    "Cyl' #",
    "platform",
    "Troubleshooting",
] as const;
