export const PATHS = {
    dashboard: "/dashboard",
    board: "/board",
    boardCreate: "/board/create",
    boardEdit: (id: string) => `/board/${id}/edit`,
    reportList: "/report",
    reportCreate: "/reportcreate",
    tbmList: "/tbm",
    tbmCreate: "/tbm/create",
    workload: "/workload",
    expenseTeam: "/expense/member",
    expensePersonal: "/expense",
    vacation: "/vacation",
    members: "/members",
    vehicles: "/vehicles",
} as const;
