export const PATHS = {
    dashboard: "/dashboard",
    board: "/board",
    boardCreate: "/board/create",
    boardView: (id: string) => `/board/${id}`,
    boardEdit: (id: string) => `/board/${id}/edit`,
    scheduleList: "/schedule",
    scheduleCreate: "/schedule/create",
    reportList: "/report",
    reportCreate: "/reportcreate",
    invoice: "/invoice",
    invoiceDrafts: "/invoice/drafts",
    invoiceCreate: "/invoice/create",
    tbmList: "/tbm",
    tbmCreate: "/tbm/create",
    workload: "/workload",
    expenseTeam: "/expense/member",
    expensePersonal: "/expense",
    materialsList: "/materials",
    materialsCreate: "/materials/create",
    vacation: "/vacation",
    members: "/members",
    vehicles: "/vehicles",
} as const;
